env:
  es6: true
  node: true
  jest: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
  ecmaVersion: 8
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - backtick
  semi:
    - error
    - never
  no-console: 1
